---
- name: Synchronize wp-content
  synchronize:
    src: files/wp-content
    dest: /var/www/comainu
    recursive: yes
    compress: yes

- name: Synchronize import file
  synchronize:
    src: "{{wpc_import_sql_file}}"
    dest: /tmp/dump.sql.gz

- name: Import sql
  mysql_db:
    name: "{{wpc_db_name}}"
    state: import
    login_user: "{{wpc_db_login_user}}"
    login_password: "{{wpc_db_login_password}}"
    target: /tmp/dump.sql.gz

- name: Replace siteurl and home
  command: mysql -u{{wpc_db_login_user}} -p{{wpc_db_login_password}} {{wpc_db_name}} -e "UPDATE wp_options SET option_value='{{wpc_url}}' WHERE option_name IN ('siteurl','home')"
